# Site settings
title: "Arman's Tech Blog"
description: "Expert insights on coding, software engineering, AI, and technology from a seasoned developer with 15+ years of experience."
author: "Arman"
avatar: "/assets/images/profile.jpg"
twitter: "https://twitter.com/your-twitter"
github: "https://github.com/your-github"
default_image: "/assets/images/default-social.jpg"
url: "https://www.armannotes.com"
baseurl: ""

# SEO settings
twitter_username: your-twitter-handle
github_username: your-github-handle
linkedin_username: your-linkedin
google_analytics: UA-XXXXXXXX-X

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-last-modified-at

# Collections
collections:
  categories:
    output: true
    permalink: /category/:name/
  tags:
    output: true
    permalink: /tag/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      sharing: true
  - scope:
      path: ""
    values:
      image: "/assets/images/default-social.jpg"

# Compression
sass:
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
