# Site settings
title: "Arman's Tech Blog"
description: "Expert insights on coding, software engineering, AI, and technology from a seasoned senior software developer with 18+ years of experience."
author: "Arman"
avatar: "/img/me.jpg"
twitter: "https://x.com/programmerByDay"
github: "https://github.com/armannaj"
bluesky: "https://bsky.app/profile/armannaj.bsky.social"
default_image: "/assets/images/default-social.jpg"
url: "https://www.armannotes.com"
baseurl: ""

# SEO settings
twitter_username: programmerByDay
github_username: armannaj
linkedin_username: your-linkedin
google_analytics: UA-XXXXXXXX-X

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page/:num/"

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-last-modified-at

# Collections
collections:
  tags:
    output: true
    permalink: /tag/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      sharing: true
  - scope:
      path: ""
    values:
      image: "/assets/images/default-social.jpg"

# Compression
sass:
  sass_dir: _sass
  style: compressed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
